config/routes.rb
Rails.application.routes.draw do


  root 'urls#index'
  resources :urls
  get 'c/:code', to:'portal#redirector'

  get '/login', to: 'auth#index'
  post '/login', to: 'auth#login'
  delete '/logout', to: 'auth#delete'
  get 'register', to: 'users#register'
  get 'users', to: 'users#index'
  post 'register', to: 'users#create'


  namespace :api do
    resources :urls
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :origin, presence: true
  validates :code, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/api/urls_controller.rb
class Api::UrlsController < ActionController::API
    include Generator
    include ApiResponse
    
    before_action :get_header_attr
    
    
    def get_header_attr
        @secretKey = request.headers["Secret-Key"]
        
        if @secretKey != "8dD87eFH9o7nV"
            render json: { message: "Secret key does't valid!", code: 401}, status: 401 
        end

    end

    #GET /api/v1/create
    def create        
        @generatedStr = random_string(5)

        if params[:code]
            @code = params[:code]
        else
            @code =  @generatedStr
        end

        @url = Url.create(code:  @code, origin: params[:origin])

        if @url.valid?
            render json: { message: "Url successfully store", data: @url}, status: 200 
        else 
            render json: { error: "Unable to store the URL",  errors: @url.errors}, status: 400 
        end

    end

    #PUT /api/v1/:id
    def update
        @url = Url.find(params[:id])
        if @url
            @url.update(code:  @code, origin: params[:origin])
            render json: { message: "Url successfully updated"}, status: 200 
        else 
            render json: { error: "Unable to update the URL"}, status: 400 
        end
    end

    def index
        @urls = Url.all 
        render json: {message: "Success load data", data: @urls}
    end

    def destroy
        @url = Url.find(params[:id])
        if @url
            @url.destroy
            render json: { message: "Success delete"}, status: 200 
        else 
            render json: { error: "Unable to delete"}, status: 400 
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def authenticate
    current_session = session[:user_id]
    redirect_to login_path, notice: 'Please sign in' if current_session.blank?
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :authenticate, only: [:delete]

  def index

  end
  def login
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to urls_path
    else
      redirect_to login_path
    end
  end

  def delete
    session.clear

    redirect_to login_path, notice: 'Sign out success!'
  end
end

app/controllers/concerns/api_response.rb
module ApiResponse
    def success(message, data)
        render json: {message: message, data: data}, status: 200
    end
    
    def error_invalid_parameters(exception)
        render json: { 'error': 'Invalid parameters: ' + exception.params.to_s },
               status: 422
    end
    
    def error_bad_request(exception)
        render json: { 'error': 'Bad Request',
                       'exception': exception.inspect }, status: 422
    end
    
    def error_record_invalid(exception)
        render json: { 'warning': 'Validation failed. :(. See exception for more' \
                                  'details. Generation aborted.',
                       "exception": exception.inspect,
                       "record": exception.record }, status: 201
      end
end

app/controllers/concerns/generator.rb
module Generator
    def random_string(length)
        charset = Array('A'..'Z') + Array(0..9)
        Array.new(length) { charset.sample }.join
    end
end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  def redirector
    @url = Url.find_by(code: params[:code])
    if @url
      redirect_to @url.origin
    else
      render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def login
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show edit update destroy ]
  before_action :authenticate
  include Generator
  # GET /urls or /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1 or /urls/1.json
  def show
  end

  # GET /urls/register
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls or /urls.json
  def create
    @generatedStr = random_string(5)

    if params[:url][:code] != ""
      @code = params[:url][:code]
    else
      @code =  @generatedStr
    end

      @url = Url.create(code:  @code, origin: params[:url][:origin])

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: "Url was successfully created." }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1 or /urls/1.json
  def update
    @url = Url.find(params[:id])
    if params[:url][:code] != ""
      @code = params[:url][:code]
    else
      @code =  @generatedStr
    end
    respond_to do |format|
      if @url.update(code:  @code, origin: params[:url][:origin])
        format.html { redirect_to @url, notice: "Url was successfully updated." }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1 or /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: "Url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.require(:url).permit(:origin, :code)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def register
    @user = User.new
  end

  def index
    @user = User.all
  end


  def create
    @user = User.create(username: params[:username], password: params[:password])
    session[:user_id] = @user.id
    redirect_to '/'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/portal_helper.rb
module PortalHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shorten URL</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<% if current_page?(login_path) || current_page?(register_path) %>
  <%= yield %>
<% else %>
  <body>
  <%= render 'shared/header' %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <%= render 'shared/sidebar' %>
      </div>
      <main class="col-md-9 bd-content">
        <%= render "shared/alert" %>
        <%= yield %>
      </main>
    </div>
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
<% end %>
</html>

app/views/shared/_alert.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mb-4" role="alert">
    <%= raw(flash[:notice]) %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show mb-4" role="alert">
    <%= raw(flash[:alert]) %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:error] %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= flash[:error] %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<% if flash[:success] %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= flash[:success] %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/shared/_header.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-2 px-md-4 mb-4 bg-white border-bottom">
  <h5 class="my-0 mr-md-auto font-weight-normal">Shorten URL</h5>
  
  <%=  button_to 'Sign out', logout_path, method: :delete, class: 'btn btn-outline-primary' %>
</div>

app/views/shared/_sidebar.html.erb
<nav class="nav flex-column">
  <%= link_to "Shorten", urls_path, class:"nav-link active" %>
  <%= link_to "Users", users_path, class: "nav-link" %>
  <a class="nav-link" href="#">Other</a>
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
</nav>

app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <div class="bd-callout bd-callout-info">
        <p><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</p>
      </div>
      
      <div class="alert alert-danger">
        <ul>
          <% url.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :origin %>
    <%= form.text_field :origin, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :code %>
    <%= form.text_field :code, class:"form-control" %>
  </div>

  <div class="form-group">
    <%=  form.submit 'Submit', :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Urls</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Origin</th>
      <th scope="col">Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.origin %></td>
        <td><%= url.code %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @url.origin %>
</p>

<p>
  <strong>Code:</strong>
  <%= @url.code %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col">Origin</th>
  </tr>
  </thead>

  <tbody>
  <% @user.each do |url| %>
    <tr>
      <td><%= url.username %></td>
<!--      <td><%#= link_to 'Show', url %></td>-->
<!--      <td><%#= link_to 'Edit', edit_url_path(url) %></td>-->
<!--      <td><%#= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/users/register.html.erb
<body class="text-center login-page">

<%= form_with(url: register_url, class: 'form-signin') do |f|%>
  <%= image_tag 'logo.png', class: 'mb-4', alt: 'Logo', height: '72' %>

  <%= render 'shared/alert' %>

  <div class="form-group">
    <label for="inputEmail" class="sr-only mb-2">Username</label>
    <%= f.text_field :username, class: 'form-control', placeholder: 'Username', required: true, autofocus: true %>
  </div>

  <div class="form-group">
    <label for="inputPassword" class="sr-only">Password</label>
    <%= f.password_field :password, class: 'form-control', placeholder: 'Password', required: true %>
  </div>
  <div class="form-group">
    <%= f.submit "Register", class: 'btn btn-lg btn-primary btn-block' %>
  </div>

<%end%>

</body>


<style>
    html,
    body {
        height: 100%;
    }

    body {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-align: center;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }
    .form-signin .checkbox {
        font-weight: 400;
    }
    .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;        padding: 10px;
        font-size: 16px;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>